config/routes.rb
Rails.application.routes.draw do
  root 'bicycles#index'

  devise_for :users
  resources :bicycles  do
    post :use, on: :member
  end

  resources :suggestions do
    put :merge
  end

  namespace :users do
    resources :bicycles
  end

end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can %i[use read], Bicycle
    can :create, Suggestion
    can :manage, Bicycle, user_id: user.id
    can :manage, Suggestion, bicycle: { user_id: user.id }
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/bicycle.rb
class Bicycle < ApplicationRecord

  belongs_to :user
  belongs_to :category
  has_many :suggestion
  has_many :usages

  mount_uploader :bicycle_photo, BicyclePhotoUploader
  validates :bicycle_photo, presence: true
  validates :name, uniqueness: true

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      Bicycle.all
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :bicycle

end

app/models/suggestion.rb
class Suggestion < ApplicationRecord

  belongs_to :bicycle
  validates :bicycle_id, uniqueness: true

end

app/models/usage.rb
class Usage < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bicycles
  has_many :usages
  has_many :suggestions

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController

  def index
    @bicycles = Bicycle.search(params[:name]).page(params[:page]).per(5)
                       .where.not(id: try(:current_user).try(:usages).try(:pluck, :bicycle_id))

    if params[:category_id].present?
      @bicycles = @bicycles.where(category_id: params[:category_id])
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @bicycle = Bicycle.new
    @category = Category.all
  end

  def create
    @category = Category.all
    @bicycle = Bicycle.create(bicycle_params)
    @bicycle.user_id = current_user.id

    respond_to do |format|
      if @bicycle.save
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully created.' }
        format.json { render :show, status: :created, location: @bicycle }
      else
        @categories = Category.all
        format.html { render :new }
      end
    end
  end

  def show
    @bicycle = Bicycle.find(params[:id])
    @suggestions = @bicycle.suggestion
  end

  def use
    current_user.usages.create(bicycle_id: params[:id])

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Success!' }
      format.js
    end
  end

  private

  def search_params
    params.permit(:name, :category_id)
  end

  def bicycle_params
    params.require(:bicycle).permit(:name, :description, :bicycle_photo, :category_id)
  end

end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_suggestion, only: %i[destroy merge]

  def new
    @bicycle = Bicycle.find(params[:id])
    @suggestion = Suggestion.new(@bicycle.attributes.except('user_id', 'bicycle_img', 'bicycle_photo'))
  end

  def create
    @suggestion = Suggestion.new(suggestion_params)
    if @suggestion.save
      redirect_to bicycle_path(id: @suggestion.bicycle.id)
    else
      render 'new'
    end
  end

  def destroy
    @suggestion.destroy if @suggestion.bicycle.user == current_user
    redirect_to root_path
  end

  def merge
    @bicycle = @suggestion.bicycle
    if @bicycle.user == current_user
      @suggestion.bicycle.update(@suggestion.attributes.except('bicycle_id', 'id'))
      @bicycle.save
      @suggestion.destroy
      redirect_to root_path
    end
  end

  private

  def suggestion_params
    params.require(:suggestion).permit(:name, :description,
                                       :category_id,
                                       :bicycle_id)
  end

  def find_suggestion
    @suggestion = Suggestion.find(params[:suggestion_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/bicycles/_bicycles.html.erb
  <% @bicycles.each do |bicycle| %>
      <div id="<%= bicycle.id%>">
        <%= image_tag bicycle.bicycle_photo.url, style: "width: 500px;height: 300px;"%>
        <h2 style=""><%= link_to bicycle.name, bicycle_path(id: bicycle.id) %></h2>
        <p><%= truncate(bicycle.description, length: 300) %></p>
        <%= link_to 'Use', use_bicycle_path(bicycle), remote: true, method: :post, class: 'btn btn-danger' if current_user.present? %>
        <hr>
      </div>
  <% end %>
<%= paginate @bicycles %>

app/views/bicycles/_form.html.erb
<div class="box">
  <%= form_for @bicycle,  multiple: true do |b|%>

      <div class="form-group">
        <%= b.label :name, :class => 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= b.text_field :name, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= b.label :description, :class => 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= b.text_field :description, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= b.label :bicycle_photo, :class => 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= b.file_field :bicycle_photo, :class => 'form-control'%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-lg-10">
          <%= b.collection_select :category_id, @category, :id, :title%>
        </div>
      </div>

      <div class="col-lg-10">
        <%= b.submit 'Create', class: 'btn'%>
      </div>

  <%end%>
</div>

app/views/bicycles/index.html.erb
<%= form_tag root_path, method: :get , remote: true do %>
    <%= text_field_tag :name %>
    <%= select_tag :category_id,
                   options_from_collection_for_select(Category.all, :id, :title),
                   prompt: 'choose category' %>
    <%= submit_tag 'Search' %>
<% end %>

<div id="search_result">
  <%= render "bicycles" %>
</div>

app/views/bicycles/index.js.erb
$('#search_result').html('<%= escape_javascript (render partial:'bicycles' )%>')

app/views/bicycles/new.html.erb
<%= render "bicycles/form" %>

app/views/bicycles/show.html.erb
<%= image_tag @bicycle.bicycle_photo.url, style: 'width: 300px' if @bicycle.bicycle_photo.present? %>
<h2><%= @bicycle.name %></h2>
<p><%= @bicycle.description %></p>

<%= link_to 'Create suggestion', new_suggestion_path(id: @bicycle.id) %>


<div class="suggestions">
  <h2>Suggestions:</h2>
  <% @suggestions.each do |suggestion| %>
      <h3><%= suggestion.name %></h3>
      <p><%= suggestion.description %></p>
      <br>
      <% if @bicycle.user == current_user %>
          <%= link_to 'Merge suggestion', suggestion_merge_path(suggestion_id: suggestion.id), method: :put %>
          <%= link_to 'Delete suggestion', suggestion_path(suggestion_id: suggestion.id), method: :delete %>
      <% end %>
  <% end %>
</div>

app/views/bicycles/use.js.erb
$(document.getElementById(<%= params[:id].to_i %>)).hide(500);

app/views/layouts/_head.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <%= link_to 'coax test', root_path, :class => "navbar-brand" %>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <% if user_signed_in? %>
        <ul class="nav navbar-nav pull-right active">
          <li><%= link_to "add", new_bicycle_path %></li>
          <li class="active">  <%= link_to "Exit", destroy_user_session_path, :method => :delete %> </li>
        </ul>

    <% else %>

        <ul class="nav navbar-nav pull-right active">
          <li class="active"> <%= link_to "Sing up", new_user_registration_path %> </li>
          <li class="active"><%= link_to "Sing in", new_user_session_path %> </li>
        </ul>

    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoaxTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/head" %>
    <%= yield %>
  </body>
</html>

app/views/suggestions/new.html.erb
<div class="box">
  <%= form_for @suggestion do |b| %>

      <div class="form-group">
        <%= b.label :name, :class => 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= b.text_field :name, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= b.label :description, :class => 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= b.text_field :description, :class => 'form-control' %>
        </div>
      </div>

      <br>
      <div class="form-group">
        <div class="col-lg-10">
          <%= b.select :category_id, Category.all.collect { |c| [c.title, c.id] } %>        </div>
      </div>

      <br>
      <div class="col-lg-10">
        <%= b.submit 'Create', class: 'btn'%>
      </div>

  <%end%>
</div>